### ISSUE TITLE
Upload to Firefox Addons

### ISSUE THREAD

**Issue by tuskiie** [jtucker2/Reddit-Auto-Dark-Mode#1]
Would you consider uploading the extension to the Firefox Addons website? I tested the extension myself and I'm pretty sure it works no issue.

**Comment by jtucker2** [comment]
The extension has been updated for the Firefox Add-ons website and is under review! Will close this issue when it is accepted. Sorry for how long this took 😅

**Comment by jtucker2** [comment]
The extension is now live on the Add-ons website [here](https://addons.mozilla.org/en-GB/firefox/addon/reddit-auto-dark-mode)!
